version: '3.9'

services:
  nginx:
    container_name: angular-reports-dashboard
    image: angular-reports-dashboard
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
